services:
  db:
    image: postgres:9
    ports:
      - "9999:5432"
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orders
    volumes:
      - ./data/database:/var/lib/postgresql/data
#  sonarqube:
#    image: sonarqube
#    ports:
#      - 9001:9000
